namespace Gresst.Application.DTOs;

/// <summary>
/// Input for registering waste generated by a company at its own facility.
/// Creates Residuo + Saldo (inventory) directly; no Request (Solicitud) is involved.
/// See docs/waste-generation.md.
/// </summary>
public class RegisterGeneratedWasteDto
{
    /// <summary>Generator (company/person) ID. Maps to Residuo.IdPropietario.</summary>
    public string GeneratorPersonId { get; set; } = string.Empty;

    /// <summary>Depot (site/facility) where waste is generated. Maps to Saldo.IdDeposito.</summary>
    public long DepotId { get; set; }

    /// <summary>Material/waste type. Maps to Residuo.IdMaterial.</summary>
    public long MaterialId { get; set; }

    /// <summary>Quantity (units). Stored in Saldo.Cantidad.</summary>
    public decimal? Quantity { get; set; }

    /// <summary>Weight. Stored in Saldo.Peso.</summary>
    public decimal? Weight { get; set; }

    /// <summary>Volume. Stored in Saldo.Volumen.</summary>
    public decimal? Volume { get; set; }

    /// <summary>Optional description. Maps to Residuo.Descripcion.</summary>
    public string? Description { get; set; }

    /// <summary>Optional reference/code. Maps to Residuo.Referencia.</summary>
    public string? Reference { get; set; }

    /// <summary>Optional treatment ID. Stored in Saldo.IdTratamiento.</summary>
    public long? TreatmentId { get; set; }
}
