using Gresst.Application.DTOs;

namespace Gresst.Application.Services;

/// <summary>
/// Registers waste generated by a company at its own facility.
/// Creates Residuo + Saldo (inventory) directly; no Request (Solicitud) is involved.
/// See docs/waste-generation.md.
/// </summary>
public interface IWasteGenerationService
{
    /// <summary>
    /// Registers generated waste: inserts Residuo and Saldo in one transaction.
    /// </summary>
    Task<RegisteredWasteResultDto> RegisterGeneratedWasteAsync(
        RegisterGeneratedWasteDto dto,
        CancellationToken cancellationToken = default);
}
